[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solperp_anchor = "7oYnX6upn2jhobcxUoarHs7MyyiF7ieZgzMGcjfQhrrD"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
